name: Repository Structure Validation

on:
  workflow_dispatch:

jobs:
  validate-structure:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check for branches other than master
        run: |
          echo "Checking branches..."
          branches=$(git branch -r | sed 's/^[[:space:]]*//' | grep -v '^origin/HEAD')
          echo "Found branches: $branches"
          
          extra_branches=$(echo "$branches" | grep -v '^origin/master$' || true)
          
          if [ -n "$extra_branches" ]; then
            echo "❌ ERROR: Extra branches found:"
            echo "$extra_branches"
            exit 1
          fi
          echo "✅ PASS: Only master branch exists"

      - name: Check for markdown files
        run: |
          echo "Checking markdown files..."
          
          if [ ! -f "README.md" ]; then
            echo "❌ ERROR: README.md not found in root"
            exit 1
          fi
          
          # Find all .md files in root only
          root_md=$(find . -maxdepth 1 -name "*.md" -type f)
          root_md_count=$(echo "$root_md" | wc -l)
          
          echo "Markdown files in root: $root_md_count"
          echo "$root_md"
          
          if [ "$root_md_count" -ne 1 ]; then
            echo "❌ ERROR: Expected 1 .md file in root, found $root_md_count"
            exit 1
          fi
          
          # Check for .md files anywhere else (except .git)
          all_md=$(find . -name "*.md" -type f ! -path "./.git/*" ! -path "./README.md")
          
          if [ -n "$all_md" ]; then
            echo "❌ ERROR: Found extra markdown files:"
            echo "$all_md"
            exit 1
          fi
          
          echo "✅ PASS: Only README.md exists in repository"

      - name: Success Summary
        if: success()
        run: echo "🎉 All checks passed!"