name: Generate Files and Update Content


on:
  create:
    branches:
      - '*'

jobs:
  generate-files:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      
      - name: Create new test files
        run: |
          python3 << 'EOF'
          from pathlib import Path
          from datetime import datetime
          
          scripts_dir = Path('scripts')
          
          # Файл 1: Документация по заданиям
          assignment_docs = """
            # 📚 Вайб-Кодинг Задания: Полная Документация
            
            ## Обзор
            
            Набор из 10 практических заданий для студентов-бакалавров 1 года
            по анализу данных (Exploratory Data Analysis).
              
            ## Технологии 
            - Python 3.8+
            - pandas — работа с данными
            - matplotlib/seaborn — визуализация
            - scikit-learn — датасеты
            
            ## Требования
            ```bash
            pip install pandas numpy matplotlib seaborn scikit-learn datasets
            ```

            ## Использование

            1. Студент получает случайное задание
            2. Работает в файле assignment.py
            3. Запускает проверки (PEP8, lint)
            4. Создаёт Pull Request
            5. После merge ветка удаляется
            ---
            Дата создания: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
            """
          
          with open(scripts_dir / 'ASSIGNMENTS_README.md', 'w') as f:
              f.write(assignment_docs)
          print("✓ Создан ASSIGNMENTS_README.md")
          
          # Файл 2: Требования к коду
          requirements = """# 📋 Требования к Коду
          
            ## Обязательные Функции
            Каждый assignment.py должен содержать:

            ### 1. load_data()
            ```python
            def load_data():
                    \"\"\"Загружает и возвращает DataFrame\"\"\"
                        pass
            ```
            Должна вернуть:
                - DataFrame с данными
                - Целевую переменную в последней колонке
                - Без пропущенных значений
                
            ### 2. target_analysis()
            ```python
            def target_analysis(df):
                    \"\"\"Анализирует целевую переменную\"\"\"
                        pass
            ```

            Должна:
            - Вывести статистику целевой переменной
            - Показать распределение значений
            - Обработать ошибки

            ### 3. feature_statistics()
            ```python
            def feature_statistics(df):
                \"\"\"Показывает статистику признаков\"\"\"
                pass
            ```

            ### 4. visualize_target()
            ```python
            def visualize_target(df):
                \"\"\"Создаёт визуализацию целевой переменной\"\"\"
                pass
            ```

            Должна:
            - Создать PNG файл
            - Название файла: NN_dataset_target_distribution.png

            ### 5. visualize_features()
            ```python
            def visualize_features(df):
                \"\"\"Создаёт визуализацию признаков\"\"\"
                pass
            ```

            ## Стиль Кода

            - PEP8 compliance
            - Max 120 символов на строку
            - Правильные отступы (4 пробела)
            - Docstrings для функций

            ---

            Версия: 1.0
            """
          
          with open(scripts_dir / 'CODE_REQUIREMENTS.md', 'w') as f:
              f.write(requirements)
          print("✓ Создан CODE_REQUIREMENTS.md")
          
          # Файл 3: Шпаргалка по pandas
          pandas_cheatsheet = """# 🐼 Pandas Шпаргалка

            ## Основные Операции

            ### Загрузка данных
            ```python
            import pandas as pd
            from sklearn.datasets import load_iris

            # Из sklearn датасета
            iris = load_iris()
            X = pd.DataFrame(iris.data, columns=iris.feature_names)
            y = pd.Series(iris.target, name='target')
            df = pd.concat([X, y], axis=1)
            ```

            ### Базовая информация
            ```python
            df.shape          # (150, 5)
            df.columns        # Index(['sepal length (cm)', ...])
            df.dtypes         # Типы данных
            df.head()         # Первые 5 строк
            df.describe()     # Статистика
            df.info()         # Информация
            ```

            ### Работа с колонками
            ```python
            df['target']           # Одна колонка
            df[['col1', 'col2']]  # Несколько колонок
            df.iloc[:, -1]        # Последняя колонка
            df.iloc[:, :-1]       # Все кроме последней
            ```

            ### Фильтрация
            ```python
            df[df['age'] > 20]
            df[(df['age'] > 20) & (df['city'] == 'NYC')]
            df[df['name'].isin(['Alice', 'Bob'])]
            ```

            ### Статистика
            ```python
            df['age'].mean()
            df['age'].std()
            df['age'].min()
            df['age'].max()
            df['category'].value_counts()
            df.groupby('category')['age'].mean()
            ```

            ### Пропущенные значения
            ```python
            df.isnull().sum()     # Количество пропусков
            df.dropna()           # Удалить пропуски
            df.fillna(0)          # Заполнить значением
            ```

            ---

            Дата: {datetime.now().strftime('%Y-%m-%d')}
            """
          
          with open(scripts_dir / 'PANDAS_CHEATSHEET.md', 'w') as f:
              f.write(pandas_cheatsheet)
          print("✓ Создан PANDAS_CHEATSHEET.md")
          
          # Файл 4: Шпаргалка по визуализации
          viz_cheatsheet = """# 📊 Matplotlib Шпаргалка

            ## Основные Графики

            ### Гистограмма
            ```python
            import matplotlib.pyplot as plt

            plt.hist(data, bins=30, edgecolor='black')
            plt.xlabel('Значение')
            plt.ylabel('Частота')
            plt.title('Распределение')
            plt.savefig('histogram.png')
            ```

            ### Boxplot
            ```python
            plt.figure(figsize=(10, 5))
            df.boxplot(column='value', by='category')
            plt.savefig('boxplot.png')
            ```

            ### Scatter
            ```python
            plt.scatter(df['x'], df['y'], alpha=0.5)
            plt.xlabel('X')
            plt.ylabel('Y')
            plt.savefig('scatter.png')
            ```

            ### Bar Chart
            ```python
            df['category'].value_counts().plot(kind='bar')
            plt.tight_layout()
            plt.savefig('bar_chart.png')
            ```

            ## Параметры

            ```python
            plt.figure(figsize=(10, 5))           # Размер
            plt.title('Title', fontsize=14)       # Заголовок
            plt.xlabel('X Label')                 # Ось X
            plt.ylabel('Y Label')                 # Ось Y
            plt.grid(True, alpha=0.3)            # Сетка
            plt.savefig('plot.png', dpi=100)     # Сохранение
            plt.show()                            # Показать
            ```

            ---

            Дата: {datetime.now().strftime('%Y-%m-%d')}
            """
          
          with open(scripts_dir / 'MATPLOTLIB_CHEATSHEET.md', 'w') as f:
              f.write(viz_cheatsheet)
          print("✓ Создан MATPLOTLIB_CHEATSHEET.md")
          
          EOF
      
      - name: Update existing files with timestamps
        run: |
          python3 << 'EOF'
          from pathlib import Path
          from datetime import datetime
          
          scripts_dir = Path('scripts')
          current_time = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
          
          # Обновляем все *_template.py файлы
          for file in sorted(scripts_dir.glob('*_template.py')):
              with open(file, 'a') as f:
                  f.write(f"\n# Последнее обновление: {current_time}\n")
              print(f"✓ Обновлён {file.name}")
          
          EOF
      
      - name: Create summary file
        run: |
          python3 << 'EOF'
          from datetime import datetime
          
          summary = f"""# 📝 Отчёт об Обновлении

            ## 🆕 Новые Файлы

            ✅ ASSIGNMENTS_README.md
            - Полная документация по заданиям
            - Структура и требования
            - Инструкции по использованию

            ✅ CODE_REQUIREMENTS.md
            - Обязательные функции
            - Требования к коду
            - Стандарты PEP8

            ✅ PANDAS_CHEATSHEET.md
            - Шпаргалка по pandas
            - Примеры операций
            - Tipи трюки

            ✅ MATPLOTLIB_CHEATSHEET.md
            - Шпаргалка по визуализации
            - Примеры графиков
            - Параметры

            ## 🔄 Обновлены Существующие Файлы
            ✅ Все *_full_analysis.py файлы
            - Добавлены временные метки
            - Несущественные изменения
            - Для отслеживания обновлений

            ## 📊 Статистика

            - Новых файлов: 4
            - Обновлено файлов: 10
            - Время выполнения: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

            ## ✅ Статус

            Все файлы успешно созданы и обновлены

            ---

            Дата: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
            """
                
          with open('FILE_UPDATE_REPORT.md', 'w') as f:
              f.write(summary)
          
          print(summary)
          
          EOF
      
      - name: Commit and push changes
        run: |
          git config --local user.email "github-actions@github.com"
          git config --local user.name "GitHub Actions"
          
          # Проверяем что есть изменения
          if [ -n "$(git status --porcelain)" ]; then
            git pull
            git add scripts/
            git add FILE_UPDATE_REPORT.md
            git commit -m "🔄 Auto-generate documentation and update files

            - Added ASSIGNMENTS_README.md
            - Added CODE_REQUIREMENTS.md
            - Added PANDAS_CHEATSHEET.md
            - Added MATPLOTLIB_CHEATSHEET.md
            - Updated all _full_analysis.py files with timestamps"
            git push origin HEAD:${{ github.ref }}
          else
            echo "No changes to commit"
          fi
      
      - name: Upload report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: file-update-report
          path: FILE_UPDATE_REPORT.md
      
      - name: Summary
        run: |
          echo "✅ Workflow завершён успешно"
          echo "📁 Создано 4 новых файла"
          echo "📝 Обновлено 10 существующих файлов"
          echo "📊 Отчёт: FILE_UPDATE_REPORT.md"
